// contents.ts
import {
    BookOpen,
    Brain,
    Target,
    Zap,
    ArrowRight,
    Search,
    Clock,
    MessageCircle,
    Sparkles,
} from "lucide-react";

export const flashcardCategories = [
    {
        id: "foundations",
        name: "Foundations",
        description: "Essential building blocks for Japanese",
        color: "from-blue-500 to-blue-600",
        icon: BookOpen,
        modules: [
            {
                id: "hiragana",
                name: "Hiragana",
                difficulty: "Beginner",
                progress: 75,
                cards: 46,
            },
            {
                id: "katakana",
                name: "Katakana",
                difficulty: "Beginner",
                progress: 60,
                cards: 46,
            },
            {
                id: "katakana_words",
                name: "Katakana Words",
                difficulty: "Intermediate",
                progress: 40,
                cards: 20,
            },
        ],
    },
    {
        id: "numbers-time",
        name: "Numbers & Time",
        description: "Practical daily use skills",
        color: "from-green-500 to-green-600",
        icon: Clock,
        modules: [
            {
                id: "numbers_basic",
                name: "Basic Numbers",
                difficulty: "Beginner",
                progress: 90,
                cards: 10,
            },
            {
                id: "numbers_extended",
                name: "Extended Numbers",
                difficulty: "Intermediate",
                progress: 45,
                cards: 20,
            },
            {
                id: "days_of_week",
                name: "Days of Week",
                difficulty: "Beginner",
                progress: 95,
                cards: 7,
            },
            {
                id: "months_complete",
                name: "Months",
                difficulty: "Beginner",
                progress: 30,
                cards: 12,
            },
        ],
    },
    {
        id: "essential-vocab",
        name: "Essential Vocabulary",
        description: "Core communication words",
        color: "from-purple-500 to-purple-600",
        icon: MessageCircle,
        modules: [
            {
                id: "greetings_essential",
                name: "Greetings",
                difficulty: "Beginner",
                progress: 85,
                cards: 15,
            },
            {
                id: "question_words",
                name: "Question Words",
                difficulty: "Beginner",
                progress: 55,
                cards: 12,
            },
            {
                id: "base_nouns",
                name: "Basic Nouns",
                difficulty: "Beginner",
                progress: 70,
                cards: 25,
            },
            {
                id: "colors_basic",
                name: "Colors",
                difficulty: "Beginner",
                progress: 80,
                cards: 10,
            },
        ],
    },
    {
        id: "grammar-structure",
        name: "Grammar & Structure",
        description: "Language building blocks",
        color: "from-orange-500 to-orange-600",
        icon: Brain,
        modules: [
            {
                id: "adjectives",
                name: "Adjectives",
                difficulty: "Intermediate",
                progress: 65,
                cards: 30,
            },
            {
                id: "verbs",
                name: "Japanese Verbs",
                difficulty: "Intermediate",
                progress: 25,
                cards: 50,
            },
            {
                id: "vocab",
                name: "Vocabulary",
                difficulty: "Intermediate",
                progress: 50,
                cards: 40,
            },
        ],
    },
];