# benky-fy/frontend/Dockerfile.dev
FROM node:18-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat

# Install deps into /app/node_modules
COPY frontend/package*.json ./
RUN npm ci

ENV NODE_ENV=development
EXPOSE 3000
